debug: false


spring:
  application:
    name: reservoir-backend-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

  datasource:
    username: root
    password: "0503"
    url: jdbc:mysql://106.52.78.230:3306/cpan?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
  thymeleaf:
    suffix: .html
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  web:
    resources:
      static-locations: classpath:/static/
  data:
    redis:
      host: 106.52.78.230        # Redis服务器主机名，默认为localhost
      port: 6379             # Redis服务器端口，默认为6379s
      password: "qwm0503"             # Redis服务器密码（如果有的话）
      database: 0            # Redis数据库索引，默认为0
      lettuce:
        pool:
          max-active: 8  # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-idle: 8    # 连接池中的最大空闲连接 默认 8
          min-idle: 0    # 连接池中的最小空闲连接 默认 0
#  mail:
#    host: smtp.163.com
#    port: 465
#    username: "itakeaway@163.com"
#    password: "VMQUTXAQXJNCCUUJ"
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#    protocol: smtps


springdoc:
  swagger-ui:
    path: /swagger-ui.html


logging:
  level:
    root: INFO
  config:
    classpath:logback-spring.xml


jwt:
  secret: qwm
  expiration: 86400

ffmpeg:
  path:
    classpath:bin/


server:
  port: 8090
#  servlet:
#    context-path: /api


min:
  config:
    http:
      debug: true